version: '3.8'

services:
  hello-bets:
    image: hello-bets-service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - config.env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend_network

  database:
    image: 'postgres:14.0'
    env_file:
      - config.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
